//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class surveyMonkeyEntities7 : DbContext
    {
        public surveyMonkeyEntities7()
            : base("name=surveyMonkeyEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveSurvey> ActiveSurveys { get; set; }
        public virtual DbSet<conductsurvey> conductsurveys { get; set; }
        public virtual DbSet<Crsdtl> Crsdtls { get; set; }
        public virtual DbSet<Question_Answer> Question_Answer { get; set; }
        public virtual DbSet<survey> surveys { get; set; }
        public virtual DbSet<surveyaudience> surveyaudiences { get; set; }
        public virtual DbSet<surveyquestion> surveyquestions { get; set; }
        public virtual DbSet<surveyresponse> surveyresponses { get; set; }
        public virtual DbSet<teacherSurvey> teacherSurveys { get; set; }
        public virtual DbSet<EMPMTR> EMPMTRs { get; set; }
        public virtual DbSet<STMTR> STMTRs { get; set; }
    }
}
