//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STMTR
    {
        public string Reg_No { get; set; }
        public string App_no { get; set; }
        public string St_firstname { get; set; }
        public string St_lastname { get; set; }
        public string St_middlename { get; set; }
        public string Father_name { get; set; }
        public string St_email { get; set; }
        public string Sex { get; set; }
        public string Marital_status { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string Nic_no { get; set; }
        public string Pr_city { get; set; }
        public string Per_city { get; set; }
        public string Sess { get; set; }
        public string Pref_1 { get; set; }
        public string Pref_2 { get; set; }
        public Nullable<System.DateTime> Adm_date { get; set; }
        public string Semester_no { get; set; }
        public string St_status { get; set; }
        public string USER_ID { get; set; }
        public string Final_course { get; set; }
        public string Enrl_status { get; set; }
        public string SOS { get; set; }
        public string Section { get; set; }
        public string Password { get; set; }
        public string Discipline { get; set; }
    }
}
