//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class surveyresponse
    {
        public int id { get; set; }
        public Nullable<int> surveyid { get; set; }
        public Nullable<int> questionid { get; set; }
        public string response { get; set; }
        public string userid { get; set; }
        public string date { get; set; }
    }
}
